CUDA_VISIBLE_DEVICES=0 accelerate launch --config_file train_settings.json train_image_transformer.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" \
  --train_data_dir='./datasets/Open_Images/' \
  --placeholder_token="S" \
  --resolution=256 \
  --train_batch_size=2 \
  --gradient_accumulation_steps=8 \
  --max_train_steps=100000 \
  --learning_rate=1e-5 --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --domain_adaptor_path "./checkpoints/domain_adaptor_200000.pt" \
  --output_dir="./checkpoints/image_transformer" \
  --save_steps 2500